-- TOOD: CREATE IF NOT EXISTS SCHEMA statement

CREATE IF NOT EXISTS TABLE `user` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `nickname` VARCHAR(100) NOT NULL,
  `email` VARCHAR(250) NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE IF NOT EXISTS TABLE `game` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `current_round` TINYINT NOT NULL DEFAULT 3,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE IF NOT EXISTS TABLE `game_user` (
  `user_id` INT,
  `game_id` INT,
  `deal_order` TINYINT,
  `user_score` SMALLINT,
  `user_hand` TEXT(500) NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  FOREIGN KEY (`user_id`)
  REFERENCES `user`(`id`),
  FOREIGN KEY (`game_id`)
  REFERENCES `game`(`id`)
  ON DELETE CASCADE
)

CREATE IF NOT EXISTS `round` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `game_id` INT NOT NULL,
  `value` TINYINT NOT NULL,
  `end_of_round` TINYINT NOT NULL DEFAULT 0,
  `deck` TEXT(1000) NOT NULL,
  `current_user_id` TINYINT NOT NULL
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  FOREIGN KEY (`game_id`)
  REFERENCES `game`(`id`)
  ON DELETE CASCADE
)
